requiredParams:
  name: Create a new screen
  description: Creates a new screen based on AbstractActivity.

widgets:
  - stringParameter:
      id: screenName
      name: Screen name (without "Activity" word)
      help: Enter the name for the screen to create (without "Activity" word)
      constraints:
        - nonempty
      default: Blank

  - booleanParameter:
      id: hasPackage
      name: Add a package for the screen
      help: Select this if the screen should has the package
      default: false

  - stringParameter:
      id: screenPackageName
      name: Screen package name
      help: Enter the name for the package for screen to create
      constraints:
        - nonempty
      default: screen
      visibility: ${hasPackage}

  - booleanParameter:
      id: hasParentComponent
      name: Add a parent component to the screen component
      help: Select this if the screen component has a parent component
      default: false

  - stringParameter:
      id: shortParentComponentName
      name: Parent component name (without "Component" word)
      help: Enter the name of the parent component for the screen component (without "Component" word)
      constraints:
        - nonempty
      default: App
      visibility: ${hasParentComponent}

  - stringParameter:
      id: parentComponentPackagePath
      name: Full path to "di" package of the parent component (including "di")
      help: Enter the full path to "di" package of the parent component (including "di")
      constraints:
        - nonempty
      default: path.to.di.package
      visibility: ${hasParentComponent}

  - stringParameter:
      id: activityName
      name: Activity name
      help: ...
      default: ${screenName}Activity
      suggest: ${screenName}Activity
      visibility: false

  - stringParameter:
      id: viewBindingName
      name: ViewBinding name
      help: ...
      default: Activity${screenName}Binding
      suggest: Activity${screenName}Binding
      visibility: false

  - stringParameter:
      id: navigatorName
      name: Navigator name
      help: ...
      default: ${activityName}Navigator
      suggest: ${activityName}Navigator
      visibility: false

  - stringParameter:
      id: navigatorFactoryName
      name: NavigatorFactory name
      help: ...
      default: ${navigatorName}Factory
      suggest: ${navigatorName}Factory
      visibility: false

  - stringParameter:
      id: viewModelName
      name: ViewModel name
      help: ...
      default: ${activityName}ViewModel
      suggest: ${activityName}ViewModel
      visibility: false

  - stringParameter:
      id: viewModelFactoryName
      name: ViewModelFactory name
      help: ...
      default: ${viewModelName}Factory
      suggest: ${viewModelName}Factory
      visibility: false

  - stringParameter:
      id: componentName
      name: Component name
      help: ...
      default: ${activityName}Component
      suggest: ${activityName}Component
      visibility: false

  - stringParameter:
      id: componentHolderName
      name: Component holder name
      help: ...
      default: ${activityName}ComponentHolder
      suggest: ${activityName}ComponentHolder
      visibility: false

  - stringParameter:
      id: depsProviderName
      name: Dependencies provider name
      help: ...
      default: ${activityName}DepsProvider
      suggest: ${activityName}DepsProvider
      visibility: false

  - stringParameter:
      id: moduleName
      name: Module name
      help: ...
      default: ${activityName}Module
      suggest: ${activityName}Module
      visibility: false

  - stringParameter:
      id: injectorName
      name: Injector name
      help: ...
      default: ${activityName}Injector
      suggest: ${activityName}Injector
      visibility: false

  - stringParameter:
      id: layoutName
      name: Layout name
      help: ...
      default: activity_${screenName.classToResource()}
      suggest: activity_${screenName.classToResource()}
      visibility: false

  - stringParameter:
      id: navGraphName
      name: Navigation graph name
      help: ...
      default: graph_${screenName.classToResource()}
      suggest: graph_${screenName.classToResource()}
      visibility: false

recipe:
  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/Activity.kt.ftl
            to: ${srcOut}/${screenPackageName}/${activityName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/Activity.kt.ftl
            to: ${srcOut}/${activityName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/Navigator.kt.ftl
            to: ${srcOut}/${screenPackageName}/${navigatorName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/Navigator.kt.ftl
            to: ${srcOut}/${navigatorName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/ViewModel.kt.ftl
            to: ${srcOut}/${screenPackageName}/${viewModelName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/ViewModel.kt.ftl
            to: ${srcOut}/${viewModelName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/component/Component.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/component/${componentName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/component/Component.kt.ftl
            to: ${srcOut}/di/component/${componentName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/holder/ComponentHolder.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/holder/${componentHolderName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/holder/ComponentHolder.kt.ftl
            to: ${srcOut}/di/holder/${componentHolderName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/component/deps_provider/DepsProvider.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/component/deps_provider/${depsProviderName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/component/deps_provider/DepsProvider.kt.ftl
            to: ${srcOut}/di/component/deps_provider/${depsProviderName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/module/Module.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/module/${moduleName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/module/Module.kt.ftl
            to: ${srcOut}/di/module/${moduleName}.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/module/navigator/NavigatorFactoryModule.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/module/navigator/NavigatorFactoryModule.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/module/navigator/NavigatorFactoryModule.kt.ftl
            to: ${srcOut}/di/module/navigator/NavigatorFactoryModule.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/module/view_model/ViewModelFactoryModule.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/module/view_model/ViewModelFactoryModule.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/module/view_model/ViewModelFactoryModule.kt.ftl
            to: ${srcOut}/di/module/view_model/ViewModelFactoryModule.kt

  - predicate:
      validIf: ${hasPackage}
      commands:
        - instantiate:
            from: /root/src/di/injector/Injector.kt.ftl
            to: ${srcOut}/${screenPackageName}/di/injector/${injectorName}.kt
      elseCommands:
        - instantiate:
            from: /root/src/di/injector/Injector.kt.ftl
            to: ${srcOut}/di/injector/${injectorName}.kt

  - instantiate:
      from: /root/res/layout/activity_layout.xml.ftl
      to: ${resOut}/layout/${layoutName}.xml

  - instantiate:
      from: /root/res/navigation/nav_graph.xml.ftl
      to: ${resOut}/navigation/${navGraphName}.xml